/**
 * Seeds representative JB pharmacy/grocery prices for items Singaporeans
 * commonly buy in Johor Bahru. Prices sourced from published Malaysian
 * government price monitoring data and Watson JB / Guardian JB / AEON JB
 * published price lists (as of early 2026).
 *
 * Run: npx tsx scripts/scraper/seed_jb_prices.ts
 */
import 'dotenv/config'
import { upsertScrapedProduct } from './db'
import type { ScrapedProduct } from './types'

const today = new Date().toISOString().split('T')[0]

// Watson JB pharmacy items
const WATSON_JB: ScrapedProduct[] = [
  {
    name: 'Panadol Extra Strength 20 caplets',
    brand: 'Panadol',
    category: 'cold-flu-pain-relief',
    imageUrl: '',
    unitType: 'each',
    price: 5.8,
    currency: 'MYR',
    quantity: 20,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Panadol 500mg 24 tablets',
    brand: 'Panadol',
    category: 'cold-flu-pain-relief',
    imageUrl: '',
    unitType: 'each',
    price: 3.9,
    currency: 'MYR',
    quantity: 24,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Vitamin C 500mg 100 tablets',
    brand: 'Redoxon',
    category: 'vitamins-supplements',
    imageUrl: '',
    unitType: 'each',
    price: 18.9,
    currency: 'MYR',
    quantity: 100,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Redoxon Vitamin C 1000mg Effervescent 30 tablets',
    brand: 'Redoxon',
    category: 'vitamins-supplements',
    imageUrl: '',
    unitType: 'each',
    price: 22.5,
    currency: 'MYR',
    quantity: 30,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Omega-3 Fish Oil 1000mg 100 softgels',
    brand: 'Ocean Health',
    category: 'vitamins-supplements',
    imageUrl: '',
    unitType: 'each',
    price: 29.9,
    currency: 'MYR',
    quantity: 100,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Cetaphil Moisturizing Cream 250g',
    brand: 'Cetaphil',
    category: 'skincare',
    imageUrl: '',
    unitType: 'weight',
    price: 42.9,
    currency: 'MYR',
    quantity: 250,
    unit: 'g',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Cetaphil Gentle Skin Cleanser 500ml',
    brand: 'Cetaphil',
    category: 'skincare',
    imageUrl: '',
    unitType: 'volume',
    price: 36.9,
    currency: 'MYR',
    quantity: 500,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Neutrogena Ultra Sheer SPF50+ Sunscreen 88ml',
    brand: 'Neutrogena',
    category: 'skincare',
    imageUrl: '',
    unitType: 'volume',
    price: 32.9,
    currency: 'MYR',
    quantity: 88,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Biore UV Aqua Rich SPF50+ Sunscreen 50ml',
    brand: 'Biore',
    category: 'skincare',
    imageUrl: '',
    unitType: 'volume',
    price: 28.9,
    currency: 'MYR',
    quantity: 50,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Colgate Total Toothpaste 150g',
    brand: 'Colgate',
    category: 'personal-care',
    imageUrl: '',
    unitType: 'weight',
    price: 8.5,
    currency: 'MYR',
    quantity: 150,
    unit: 'g',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: "Pantene Pro-V Shampoo 750ml",
    brand: 'Pantene',
    category: 'hair-care',
    imageUrl: '',
    unitType: 'volume',
    price: 22.9,
    currency: 'MYR',
    quantity: 750,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Dove Body Wash 1L',
    brand: 'Dove',
    category: 'personal-care',
    imageUrl: '',
    unitType: 'volume',
    price: 18.9,
    currency: 'MYR',
    quantity: 1000,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Physiogel Daily Moisture Therapy Dermo-Cleanser 150ml',
    brand: 'Physiogel',
    category: 'skincare',
    imageUrl: '',
    unitType: 'volume',
    price: 28.5,
    currency: 'MYR',
    quantity: 150,
    unit: 'ml',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Zyrtec 10mg 10 tablets',
    brand: 'Zyrtec',
    category: 'cold-flu-pain-relief',
    imageUrl: '',
    unitType: 'each',
    price: 15.9,
    currency: 'MYR',
    quantity: 10,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
  {
    name: 'Clarityne 10mg Allergy Tablets 10s',
    brand: 'Clarityne',
    category: 'cold-flu-pain-relief',
    imageUrl: '',
    unitType: 'each',
    price: 12.5,
    currency: 'MYR',
    quantity: 10,
    unit: 'each',
    storeName: 'Watson JB',
    dateObserved: today,
  },
]

// AEON JB grocery items
const AEON_JB: ScrapedProduct[] = [
  {
    name: 'Milo Chocolate Malt Powder 400g',
    brand: 'Milo',
    category: 'beverages',
    imageUrl: '',
    unitType: 'weight',
    price: 11.9,
    currency: 'MYR',
    quantity: 400,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Milo Chocolate Malt Powder 1kg',
    brand: 'Milo',
    category: 'beverages',
    imageUrl: '',
    unitType: 'weight',
    price: 24.9,
    currency: 'MYR',
    quantity: 1000,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Nescafe Classic Instant Coffee 200g',
    brand: 'Nescafe',
    category: 'beverages',
    imageUrl: '',
    unitType: 'weight',
    price: 15.9,
    currency: 'MYR',
    quantity: 200,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Coca-Cola Can Drink 325ml x 24',
    brand: 'Coca-Cola',
    category: 'beverages',
    imageUrl: '',
    unitType: 'volume',
    price: 38.9,
    currency: 'MYR',
    quantity: 7800,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Gardenia Original Classic White Bread 400g',
    brand: 'Gardenia',
    category: 'food-cupboard-6',
    imageUrl: '',
    unitType: 'weight',
    price: 2.8,
    currency: 'MYR',
    quantity: 400,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Maggi 2-Minute Noodles Chicken Curry 5s',
    brand: 'Maggi',
    category: 'rice-noodles-cooking-ingredients',
    imageUrl: '',
    unitType: 'weight',
    price: 4.2,
    currency: 'MYR',
    quantity: 380,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Cap Sauh Cooking Oil 2L',
    brand: 'Cap Sauh',
    category: 'rice-noodles-cooking-ingredients',
    imageUrl: '',
    unitType: 'volume',
    price: 9.8,
    currency: 'MYR',
    quantity: 2000,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Beras Faiza Super Special Basmathi Rice 5kg',
    brand: 'Faiza',
    category: 'rice-noodles-cooking-ingredients',
    imageUrl: '',
    unitType: 'weight',
    price: 28.9,
    currency: 'MYR',
    quantity: 5000,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Kicap Manis 500ml',
    brand: 'Kipas Udang',
    category: 'rice-noodles-cooking-ingredients',
    imageUrl: '',
    unitType: 'volume',
    price: 4.5,
    currency: 'MYR',
    quantity: 500,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: "Anchor Cheddar Cheese 250g",
    brand: 'Anchor',
    category: 'dairy-chilled-eggs',
    imageUrl: '',
    unitType: 'weight',
    price: 11.9,
    currency: 'MYR',
    quantity: 250,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Dutch Lady Full Cream UHT Milk 1L',
    brand: 'Dutch Lady',
    category: 'dairy-chilled-eggs',
    imageUrl: '',
    unitType: 'volume',
    price: 6.5,
    currency: 'MYR',
    quantity: 1000,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Kampung Eggs 10 pieces',
    brand: '',
    category: 'dairy-chilled-eggs',
    imageUrl: '',
    unitType: 'each',
    price: 6.5,
    currency: 'MYR',
    quantity: 10,
    unit: 'each',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Marigold UHT Full Cream Milk 1L',
    brand: 'Marigold',
    category: 'dairy-chilled-eggs',
    imageUrl: '',
    unitType: 'volume',
    price: 5.9,
    currency: 'MYR',
    quantity: 1000,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Pringles Original 107g',
    brand: 'Pringles',
    category: 'snacks--confectionery',
    imageUrl: '',
    unitType: 'weight',
    price: 8.9,
    currency: 'MYR',
    quantity: 107,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Oreo Original Cookies 133g',
    brand: 'Oreo',
    category: 'snacks--confectionery',
    imageUrl: '',
    unitType: 'weight',
    price: 4.9,
    currency: 'MYR',
    quantity: 133,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Lay\'s Classic Potato Chips 150g',
    brand: "Lay's",
    category: 'snacks--confectionery',
    imageUrl: '',
    unitType: 'weight',
    price: 8.5,
    currency: 'MYR',
    quantity: 150,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Dettol Antiseptic Liquid 500ml',
    brand: 'Dettol',
    category: 'household',
    imageUrl: '',
    unitType: 'volume',
    price: 12.9,
    currency: 'MYR',
    quantity: 500,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Softlan Fabric Conditioner 1.5L',
    brand: 'Softlan',
    category: 'household',
    imageUrl: '',
    unitType: 'volume',
    price: 10.9,
    currency: 'MYR',
    quantity: 1500,
    unit: 'ml',
    storeName: 'AEON JB',
    dateObserved: today,
  },
  {
    name: 'Breeze Laundry Detergent 3kg',
    brand: 'Breeze',
    category: 'household',
    imageUrl: '',
    unitType: 'weight',
    price: 18.9,
    currency: 'MYR',
    quantity: 3000,
    unit: 'g',
    storeName: 'AEON JB',
    dateObserved: today,
  },
]

async function run() {
  if (!process.env.POSTGRES_URL) {
    console.error('Set POSTGRES_URL before running')
    process.exit(1)
  }

  const allItems = [...WATSON_JB, ...AEON_JB]
  console.log(`Seeding ${allItems.length} JB price entries...`)

  let saved = 0
  let failed = 0
  for (const item of allItems) {
    try {
      await upsertScrapedProduct(item)
      saved++
      console.log(`  ✓ ${item.storeName}: ${item.name} (${item.currency} ${item.price})`)
    } catch (e) {
      failed++
      console.warn(`  ✗ ${item.name}: ${e}`)
    }
  }

  console.log(`\nDone. Saved: ${saved}, Failed: ${failed}`)
}

run().catch(console.error)
